//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp_Exam_10.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonent()
        {
            this.Vedomost = new HashSet<Vedomost>();
        }
    
        public int Id { get; set; }
        public string Family { get; set; }
        public string Name { get; set; }
        public string Patronomyc { get; set; }
        public string Adres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vedomost> Vedomost { get; set; }
    }
}
