//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp_Exam_10.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryExam_10Entities1 : DbContext
    {
        private static LibraryExam_10Entities1 _context;

        public LibraryExam_10Entities1()
            : base("name=LibraryExam_10Entities1")
        {
        }

        public static LibraryExam_10Entities1 GetContext()
        {
            if (_context == null) _context = new LibraryExam_10Entities1();
            return _context; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonent> Abonent { get; set; }
        public virtual DbSet<Avtors> Avtors { get; set; }
        public virtual DbSet<BookFond> BookFond { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vedomost> Vedomost { get; set; }
    }
}
