//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp_Exam_10.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vedomost
    {
        public int Id_abonenta { get; set; }
        public int id_book { get; set; }
        public System.DateTime dateGive { get; set; }
        public System.DateTime dateBack { get; set; }
        public int Id { get; set; }
    
        public virtual Abonent Abonent { get; set; }
        public virtual BookFond BookFond { get; set; }
    }
}
